{
  parserClass="com.mwnciau.rblade.parser.RBladeParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="RBlade"
  psiImplClassSuffix="Impl"
  psiPackage="com.mwnciau.rblade.psi"
  psiImplPackage="com.mwnciau.rblade.psi.impl"

  elementTypeHolderClass="com.mwnciau.rblade.psi.RBladeTypes"
  elementTypeFactory="com.mwnciau.rblade.psi.RBladeTypesFactory.createElement"
  tokenTypeFactory="com.mwnciau.rblade.psi.RBladeTypesFactory.createToken"

  tokens=["RBLADE_INJECTION_IN_HTML", "RBLADE_INJECTION_IN_RUBY"]
}

rbladeFile ::= item_*

private item_ ::= (statement|HTML_TEMPLATE|COMMENT)

statement ::= RBLADE_STATEMENT (statement_parameters RBLADE_STATEMENT)?
statement_parameters ::= props | (RUBY_EXPRESSION | RBLADE_STATEMENT_COMMA | RBLADE_STATEMENT_EACH_IN)+
propName ::= RBLADE_STATEMENT_PROPS_NAME
props ::= propName RBLADE_STATEMENT RUBY_EXPRESSION (RBLADE_STATEMENT_COMMA propName RBLADE_STATEMENT RUBY_EXPRESSION)*
